export const referans =[
    {
      id:1,
      image:"./image/ajet.png",
    },
    {
      id:2,
      image:"./image/basar.png",
    },
    {
      id:3,
      image:"./image/bni.png",
    },
    {
      id:4,
      image:"./image/duran.png",
    },
    {
      id:5,
      image:"./image/freebird.png",
    },
    {
      id:6,
      image:"./image/guler.png",
    },
    {
      id:7,
      image:"./image/jms.png",
    },
    {
      id:8,
      image:"./image/kiwi.png",
    },
    {
      id:9,
      image:"./image/libraff.png",
    },
    {
      id:10,
      image:"./image/merkez.png",
    },
    {
      id:11,
      image:"./image/mga.png",
    },
    {
      id:12,
      image:"./image/pegasus.png",
    },
    {
      id:13,
      image:"./image/polyplex.png",
    },
    {
      id:14,
      image:"./image/teas.png",
    },
  ];


  export const board =[
    {
      id:1,
      image:"/image/ajet.png",
      title:"AJet",
    },
    {
      id:2,
      image:"/image/pegasus.png",
      title:"Peagsus",
    },
    {
      id:3,
      image:"/image/mga.png",
      title:"Mavi Gök Airlines",
    },
    {
      id:4,
      image:"/image/freebird.png",
      title:"Freebird Airlines",
    },
  ];

